// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtController from "./butt_controller"
application.register("butt", ButtController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import EditController from "./edit_controller"
application.register("edit", EditController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormController from "./form_controller"
application.register("form", FormController)

import MapController from "./map_controller"
application.register("map", MapController)

import MovingController from "./moving_controller"
application.register("moving", MovingController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PictureController from "./picture_controller"
application.register("picture", PictureController)

import ShareController from "./share_controller"
application.register("share", ShareController)
import SearchController from "./search_controller"
application.register("search", SearchController)

import SortingController from "./sorting_controller"
application.register("sorting", SortingController)

import ChatbaseController from "./chatbase_controller"
application.register("chatbase", ChatbaseController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TurboformController from "./turboform_controller"
application.register("turboform", TurboformController)

import KeywordController from "./keyword_controller"
application.register("keyword", KeywordController)
