# fly.toml app configuration file generated for tourmind on 2023-04-30T17:53:04+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tourmind"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
